# Fonte dos dados
source: csv                                  # csv | futwiz
data_path: "./data/futbin_export.csv"        # Usado quando source=csv

futwiz:                                      # Usado quando source=futwiz
  platform: ps                               # ps | xbox | pc
  pages: 1                                   # número de páginas do grid para scrapear
  delay_between_pages: 1.0                   # pausa entre requisições em segundos

poll_interval_secs: 20                       # Freq. que verificamos/refresh

# Limiar dos detectores
min_discount: 0.12       # 12% abaixo da média já é interessante
zscore_min: 1.8          # Z-score <= -1.8
fake_drop_pct: 0.40      # Queda >= 40% vira suspeita de fake BIN
spike_pct: 0.20          # Alta >= 20% sinaliza spike

# Alertas
cooldown_minutes: 15     # Não repetir o mesmo alerta do mesmo jogador antes desse tempo
notify_discord: true

# Histórico interno (preenche média/desvio quando faltarem no CSV/scraper)
history:
  window_minutes: 1440   # janela de análise em minutos (padrão 24h)
  max_points: 400        # máximo de pontos por jogador mantidos em memória
  min_points: 3          # mínimo de pontos para usar as métricas calculadas
